import CarType1 from "@assets/images/car-type-1.png";
import CarType2 from "@assets/images/car-type-2.png";
import CarType3 from "@assets/images/car-type-3.png";

export const DESCRIPTION = [
  {
    title: "Buy Used And New Cars Online",
    content:
      "Start your car buying journey with UCARS as we connect you seamlessly to the industry's best CaseTrust-SVTA accredited car dealerships. As a one stop car online portal you can now buy your new ride, be it a pre-owned car or a brand new car from trusted dealers all over Singapore, all in one place. Our ever expanding listing of quality and covet-worthy cars, new and second hand, from both owners and trusted car dealers, will leave you spoilt for choice. Refine your search by vehicle type, registration year, price, mileage, engine type, transmission, annual depreciation value and more to find the car that best suits your needs, taste and lifestyle. You can even search for your car by dealer or directly by owner.",
  },
  {
    title: "Sell Your Car In An Instant With Confidence",
    content:
      "We all know how selling a car in Singapore can be a daunting task especially for a first time car seller; from trying to get a valuation for your car, finding a trusted dealer, to getting the best quote on your vehicle. UCARS understands the hassle and even the costs involved and have as such partnered with Huawei to develop a FIRST in Southeast Asia AI car valuation tool that is able to provide a car’s resale value at the snap of a finger. Backed with a consortium of trusted CaseTrust-SVTA accredited car dealers you can be assured that you are getting the best price for your vehicle and do not have to worry about any hidden costs.",
  },
  {
    title: "The Ultimate Car Shopping Experience Online",
    content:
      "UCARS platform is the first of its kind to be backed by Huawei’s Artificial Intelligence and cloud computing, enabling it to be able to offer users transparency and enhanced security, all with the one aim of enhancing customer experience. So come on over to buy and sell used cars online at the best prices at UCARS Singapore. Connect easily with dealers in real-time via our online video call feature, or schedule a test drive when you're ready. Have some questions? Get them answered instantly with our chatbot moderated by our responsive team. Stay in the loop with our car-related tips, reviews and news. Learn the ins-and-outs of your car, as well as global and Singapore’s car updates at your own pace.",
  },
];
export const LIST_CARS_BRAND = [
  "Bus",
  "Lorry",
  "SUV",
  "Classic Car",
  "MPV",
  "Truck",
  "Coupe",
  "Pickup",
  "Van (Passenger)",
  "Convertible",
  "Sedan",
  "Van (Goods)",
  "Hatchback",
  "Sport Car",
  "Wagon",
];
export const LIST_CARS_ITEMS = [
  {
    id: 1,
    price: 240000,
    variants: 4,
    imgCar: CarType3,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 2,
    price: 240000,
    variants: 4,
    imgCar: CarType2,
    rentingPrice: "$2,302/mo",
    carName: "Alfa Romeo Stelvio",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 3,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "Aston Martin DBS Superlegge",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 4,
    price: 240000,
    variants: 4,
    imgCar: CarType3,
    rentingPrice: "$2,302/mo",
    carName: "Aston Martin DB11 Volante",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 5,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 6,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "Aston Martin DB11 Volante",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 7,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 8,
    price: 240000,
    variants: 4,
    imgCar: CarType3,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Wearnes Automotive",
  },
  {
    id: 9,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "EuroAutomobile",
  },
  {
    id: 10,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "EuroAutomobile",
  },
  {
    id: 11,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "EuroAutomobile",
  },
  {
    id: 12,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Performance Motors",
  },
  {
    id: 13,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Performance Motors",
  },
  {
    id: 14,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Performance Motors",
  },
  {
    id: 15,
    price: 240000,
    variants: 4,
    imgCar: CarType1,
    rentingPrice: "$2,302/mo",
    carName: "BMW X3",
    carBrand: "Performance Motors",
  },
];
